### PR TITLE
Cache the result of `_get_convert_command`

### PR DESCRIPTION
**Pull request by r-stein**
This adds a caching for the result of the `_get_convert_command`.

- it does not change, except from the edge case of installing ImageMagick while running ST (just restart ST)
- I assumed `convert_installed` to be constant time (it takes 0.05 - 0.2 s on my machine w/o caching)

### CODE REVIEW

**Comment by ig0774** [comment]
Doesn't this still cache the value if it winds up being `None` though? I agree that caching here is a good idea.

**Comment by r-stein** [comment]
Yes, it also caches `None`. I think in the edge case of installing ImageMagick while running ST one can just restart ST. You also need to restart ST if you change the path, so this should be done anyway.
The only problem I see is that the system check might succeed while `None` is still cached. We may reset the cache if the tex_path setting changes or something like that.

**Comment by ig0774** [comment]
Actually, on reflection, you're right. This is good.

**Comment by r-stein** [comment]
I have added the system check to show "restart required" for that case.

**Pull request merged**
