### PR TITLE
Created the LICENSE as represented on the github issue #1175

### PR DESCRIPTION
**Pull request by evandrocoan**
Closes https://github.com/SublimeText/LaTeXTools/issues/1175 - Can it be an open source project?

For a more organized way, anyone agreeing with the open-source license can go to the pull-request https://github.com/SublimeText/LaTeXTools/pull/1570, and hit the `review now` button at the sidebar, as shown in the following image, and type `I agree with this license for my code.` as the pull-request view message:
1. image
1. image

### CODE REVIEW

**Review by evandrocoan — COMMENTED** [review]
I agree with this license.

**Review by faergeek — APPROVED** [review]
I agree with this license for my code

**Comment by hadisfr** [comment]
I agree with this license for my code.

**Comment by randy3k** [comment]
I agree with this license for my code.

**Review by cwwwu — APPROVED** [review]
I agree with this license for my code.

**Review by hadisfr — APPROVED** [review]
I agree with this license for my code.

**Review by crypto-jeronimo — APPROVED** [review]
I agree with this license for my code.

**Pull request merged**
