### PR TITLE
more temporary filetypes to be deleted

### PR DESCRIPTION
**Pull request by mcnesium**
added some more temporary filetypes

### CODE REVIEW

**Comment by ig0774** [comment]
I wonder if the list of extensions hasn't gotten to the point where this would be better implemented through a user-customisable list in the settings, especially as we increasingly run the risk of having a default list that clobbers non-LaTeX-generated files depending on the user's setup (as happened with #491)

**Comment by msiniscalchi** [comment]
Yes, that's what I'd like to implement.

**Comment by ig0774** [comment]
This can be closed since #520 basically covers this

**Comment by mcnesium** [comment]
kthx

**Pull request closed without merging**
