### PR TITLE
Enhance cwl support

### PR DESCRIPTION
**Pull request by hadisfr**
add support of `#include:` in cwl files (appears in cwl files of TeXStudio) and some other minor improvements

### CODE REVIEW

**Comment by r-stein** [comment]
Thanks for your pull request. It looks promising

**Comment by r-stein** [comment]
Can you please retarget the pull request to the branch `version4` (top right edit and then change the branch), because we are developing our new releases on that branch.

**Comment by hadisfr** [comment]
Done! 😀

**Comment by hadisfr** [comment]
@r-stein @ig0774  any news? :-"

**Comment by r-stein** [comment]
I am sorry for the delay

**Comment by r-stein** [comment]
Release in `st3-4.0.0-alpha.9 `

**Comment by hadisfr** [comment]
Never mind. :D And Thank you. @r-stein

**Pull request merged**
