### PR TITLE
Better cite-completions

### PR DESCRIPTION
**Pull request by ig0774**
These are the same changes from #422, but done with a clean history so that it can be pulled without affecting anything other than citation completions.

### CODE REVIEW

**Comment by ig0774** [comment]
Last four commits make formatting of displayed fields a bit more consistent and address #496.

**Comment by aleth** [comment]
Nice patch queue! You might also like to add something like #315.

**Comment by ig0774** [comment]
@aleth: Thanks! I think my preference for doing something like that, however, would be to just expose all the fields to the format panel, which shouldn't be too hard against these patches. I might have a look at doing that, as it seems useful.

**Comment by ig0774** [comment]
Happier with the plugin version of this, so I'll kill this pull request.

**Pull request closed without merging**
