### PR TITLE
Typeerror can only join an iterable

### PR DESCRIPTION
**Pull request by evandrocoan**
Fix https://github.com/SublimeText/LaTeXTools/issues/1235 TypeError: can only join an iterable

### CODE REVIEW

**Comment by r-stein** [comment]
I am not sure whether we should start to guard against every misconfiguration.

**Comment by evandrocoan** [comment]
What is the misconfiguration which causes this?

**Comment by r-stein** [comment]
This just reads and joins the values of [`preview_math_template_packages`](https://github.com/SublimeText/LaTeXTools/blob/st3-4.0.0-alpha.5/LaTeXTools.sublime-settings#L142), which must be an array (as stated in the comment above it) and `preview_math_template_preamble`, which can be an array or an string (as stated in the comment above it).
Also the math scope is set as a string in the setting [`preview_math_scope`](https://github.com/SublimeText/LaTeXTools/blob/st3-4.0.0-alpha.5/LaTeXTools.sublime-settings#L117) and also an empty string should work (but is not useful) to preview the whole document.

**Comment by evandrocoan** [comment]
So the error is because the settings are empty strings?

I have not changed these default settings. Is their default value a invalid value for them?

If these lines are just reading the these settings, the settings should be validated while they are being read, then I should patch elsewhere.

**Comment by ig0774** [comment]
The links in [@rstein's comment above](https://github.com/SublimeText/LaTeXTools/pull/1236#issuecomment-334787427) point to the default values, neither of which is an empty string. The only way for the value to have changed is if you edited the local settings, which would give the behaviour you're seeing.

**Comment by evandrocoan** [comment]
When I said about empty string I was talking about the value of `preview_math_template_preamble` which @r-stein mentions on its comment.

**Comment by r-stein** [comment]
If you open the ST console and write 
```py
from LaTeXTools.latextools_utils.settings import get_setting; get_setting("preview_math_template_packages")
```
what output do you get?

**Pull request closed without merging**
