### PR TITLE
Project Overridable Settings

### PR DESCRIPTION
**Pull request by ig0774**
This is mostly a back-end change to make it easier to support overriding settings at the project level. 

Basically, these changes are designed to simplify the idiom:

```python
global_settings = sublime.load_settings('LaTeXTools.sublime-settings')
setting = view.settings().get('setting', global_settings.get('setting', default))
```

To:

```python
setting = get_setting('setting', default)
```

This, of course, assumes that the setting has the same name in the view as it does in the global settings file (I've adjusted the toggles accordingly).

However, it offers two major advantages over the usual means of doing this:
 1. In cases where a missing key would raise an exception, it will return either a specified default value or `None` if no default is supplied. This should reduce a certain class of errors, assuming the underlying code can handle the `None`.
 1.  It supports overriding dictionaries of settings in an additive way. For example, I could override the Windows `texpath` setting with a project-specific `texpath` without thereby blanking out the `distro` or `sumatra` settings.

### CODE REVIEW

**Comment by msiniscalchi** [comment]
This is excellent! Can I merge it as is?

**Comment by ig0774** [comment]
I actually want to test this a bit more before merging. There seems to be some odd behaviour with reloading when this is used from sub-packages, e.g., the `latextools_utils` package.

**Comment by msiniscalchi** [comment]
There were conflicts with the configurable tex extension patch. Nothing major---the import statements for both patches had to be combined. Hope all is OK!

**Comment by msiniscalchi** [comment]
@ig0774 I just wanted to tell you that this feature **rocks**! I played with it a bit trying to figure out what was wrong in issue #515 and I must say it's really impressive. I haven't used project files myself so far, but that may change---esp. in conjunction with the script builder in #617 .

**Pull request merged**
