### PR TITLE
Implements feature requested in #1043

### PR DESCRIPTION
**Pull request by ig0774**
Adds a command to wrap the selected text in a simple LaTeX command and automatically expands no selection to the current word. This also changes the keybindings from using snippets to using the command for emph, bold, etc. Additionally, I suppose, this makes new keybindings for new similar commands pretty trivial to implement. I've left the snippets in place so they can be used if desired, but obviously they do not have the same word-grabbing rules.

### CODE REVIEW

**Comment by r-stein** [comment]
I think this is a little bit to greedy in selecting words and we should insert a snippet if the selection is empty to easy jump-out of it.

**Comment by ig0774** [comment]
The greediness (i.e., selecting the word immediately after or immediately before the cursor) is quite intentional. That was part of the initial request. On the snippet thing: I'm not exactly sure I see inserting, e.g., `\emph{|}` without a tab-out as being that major of an inconvenience. Presumably inserting such a command means you want to add to its content...

**Comment by r-stein** [comment]
> The greediness (i.e., selecting the word immediately after or immediately before the cursor) is quite intentional. That was part of the initial request.

This does not only select words, but also other characters, e.g. if you have `foo bar.|` and press C-l,C-b you will have `foo bar\textbf{.}`.

> On the snippet thing: I'm not exactly sure I see inserting, e.g., `\emph{|}` without a tab-out as being that major of an inconvenience. Presumably inserting such a command means you want to add to its content...

The snippets usually only have a few words/one sentence, so I personally just press it, write the content, and press tab to go further.

**Comment by ig0774** [comment]
> This does not only select words, but also other characters, e.g. if you have foo bar.| and press C-l,C-b you will have foo bar\textbf{.}.

That's a good point and a limitation of the `word()` function. I suppose we can check if it's a one-character string and matches one the `word_separators` and just treat it like an empty string.

> The snippets usually only have a few words/one sentence, so I personally just press it, write the content, and press tab to go further.

Good point. I think I was thinking broadly in terms of getting this working across multiple selections, which is hard to do with snippets, where the selections might vary from one another. The common case, though, is probably just a single cursor and that could be optimised to use a snippet, I suppose.

**Comment by ig0774** [comment]
@r-stein: 1acf8ab implements what I [mentioned above](https://github.com/SublimeText/LaTeXTools/pull/1048#issuecomment-300493543). I'd be greatful if you could take a look.

**Comment by r-stein** [comment]
I would use the expand feature very conservative, because you always can just manually expand it before triggering, but not the other way.
So I would do it like this:
```
if all selections are empty and (preceded by a word character or inside a word):
    wrap the word around the selection with `textbf{....}`
else:
    insert_snippet("\textbf{${1:$SELECTION}}$0")
```

**Pull request closed without merging**
